### ISSUE TITLE
Renaming project to hook-build

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/hook-build#1]
The main purpose of this repository was to build a tool that could respond to a file being added to a repository and run a script. Due to the variability in the github events payloads it is not possible to build a generic tool for this purpose.
Specifically the github webhook pushevent does not fill in `action`: https://developer.github.com/v3/activity/events/types/#pushevent

**Comment by johnbradley** [comment]
Spoke with @dleehr and we will go with`hook-build` for this project name.

**Comment by dleehr** [comment]
@johnbradley Anything more to do here, or can this be closed?

**Comment by johnbradley** [comment]
There is nothing left to be done.
